about:
  summary: "MULTIPLY inference engine package"
  home: https://github.com/qcdis/inference-engine

package:
  name: multiply_inference_engine
  version: "0.1"

source:
  git_url: "https://github.com/qcdis/inference-engine.git"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
