language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test python=$TRAVIS_PYTHON_VERSION pytest gdal numpy typing matplotlib netcdf4 python-dateutil scipy
  - source activate test
  - pip install -U codecov
  - pip install datetime
  - pip install https://github.com/multiply-org/multiply-core/zipball/master
  - pip install https://github.com/multiply-org/prior-engine/zipball/master
  #todo change this so we only use MULTIPLY repositories
  - pip install https://github.com/jgomezdans/BRDF_descriptors/zipball/master
  - pip install https://github.com/Assimila/KaFKA/zipball/hess_corr_state_mapper
#  - pip install https://github.com/multiply-org/KaFKA-InferenceEngine/zipball/master
  - python setup.py install
  
script:
  - pytest
