name: multiply-inference-engine

channels:
  - conda-forge

dependencies:
  - python=>3.8
  - gdal=2.4
  - libgdal
  - pyproj
  - sentinelhub
  - pyyaml
  - numpy
  - scipy
  - setuptools
  - gcc=12.1.0
  - cxx-compiler
  - libgcc
  - libstdcxx-ng
  - lazrs-python
  - laspy
  - pyyaml
  - setuptools
  - pytest
  - flake8
  - scipy
  - shapely
  - netcdf4
  - pytest-shutil
  - pip
  - pip:
      - .
      - git+https://github.com/QCDIS/multiply-core.git
      - git+https://github.com/QCDIS/prior-engine.git
      - git+https://github.com/QCDIS/KaFKA-InferenceEngine.git
